CREATE DATABASE COVIDMANAGEMENT
GO

USE COVIDMANAGEMENT
GO

CREATE TABLE ACCOUNT
(
	userName VARCHAR(12) NOT NULL,
	passWordd VARCHAR(20),
	isAccount NVARCHAR(10) CHECK (isAccount = 'Admin' OR isAccount = 'Manager' OR isAccount = 'User')
)
GO

CREATE TABLE MANAGER
(
	idManager VARCHAR(12) NOT NULL,
	isFirstLogin VARCHAR(10) CHECK (isFirstLogin = 'TRUE' OR isFirstLogin = 'FALSE')
)
GO

CREATE TABLE PATIENT
(
	idPatient VARCHAR(12) NOT NULL,
	namePatient NVARCHAR(30),
	DateOfBirth DATE,
	isFirstLogin VARCHAR(10) CHECK (isFirstLogin = 'TRUE' OR isFirstLogin = 'FALSE'),
	idProvince VARCHAR(8),
	idDistrict VARCHAR(8),
	idVillage VARCHAR(8),
	street NVARCHAR(30),
	debt MONEY
)
GO

CREATE TABLE LIST_PATIENT
(
	idPatient1 VARCHAR(12) NOT NULL,
	idPatient2 VARCHAR(12) NOT NULL,	
)
GO

CREATE TABLE HISTORY_PROCESS
(
	idPatient VARCHAR(12) NOT NULL,
	statuss VARCHAR(20) NOT NULL CHECK (statuss = 'F0' OR statuss = 'F1' OR statuss = 'F2' OR statuss = 'Cured'),
	startDate DATE,
	idPlace VARCHAR(8) NOT NULL
)
GO

CREATE TABLE PLACE_OF_STATEMENT
(
	idPlace VARCHAR(8) NOT NULL,
	namePlace NVARCHAR(30),
	capacity INT,
	amountCapacity INT
)
GO

CREATE TABLE SUPPLY
(
	idSupply VARCHAR(8) NOT NULL,
	nameSupply NVARCHAR(30),
	idManager VARCHAR(12),
	imgSupply VARCHAR(20),
	unitSupply NVARCHAR(20),
	priceSupply MONEY CHECK (priceSupply > 0)
)
GO

CREATE TABLE PACKET_SUPPLY
(
	idPacket VARCHAR(8) NOT NULL,
	namePacket NVARCHAR(30),
	idManager VARCHAR(12),
	amountPacket INT,
	limitDate DATE,
	pricePacket MONEY CHECK (pricePacket > 0),
	limitPacket INT
)
GO

CREATE TABLE INCLUDEE
(
	idPacket VARCHAR(8) NOT NULL,
	idSupply VARCHAR(8) NOT NULL,
	amountSupply INT CHECK (amountSupply > 0)
)
GO

CREATE TABLE ORDERR
(
	idOrder INT NOT NULL,
	idManager VARCHAR(12),
	idPatient VARCHAR(12),
	idProduce VARCHAR(8),
	amountOrder INT CHECK (amountOrder > 0),
	sumPrice MONEY CHECK (sumPrice > 0),
	stat VARCHAR(10) CHECK (stat = 'TRUE' OR stat = 'FALSE'),
	dates DATE
)
GO

CREATE TABLE PROVINCE
(
	idProvince VARCHAR(8) NOT NULL,
	nameProvince NVARCHAR(30),
)
GO

CREATE TABLE DISTRICT
(
	idDistrict VARCHAR(8) NOT NULL,
	nameDistrict NVARCHAR(30),
)
GO

CREATE TABLE VILLAGE
(
	idVillage VARCHAR(8) NOT NULL,
	nameVillage NVARCHAR(30),
)
GO

/*SET PRIMARY KEY*/
ALTER TABLE dbo.ACCOUNT ADD PRIMARY KEY (userName)
ALTER TABLE dbo.MANAGER ADD PRIMARY KEY (idManager)
ALTER TABLE dbo.PATIENT ADD PRIMARY KEY (idPatient)
ALTER TABLE dbo.HISTORY_PROCESS ADD PRIMARY KEY (statuss, idPatient, idPlace)
ALTER TABLE dbo.PLACE_OF_STATEMENT ADD PRIMARY KEY (idPlace)
ALTER TABLE dbo.SUPPLY ADD PRIMARY KEY (idSupply)
ALTER TABLE dbo.PACKET_SUPPLY ADD PRIMARY KEY (idPacket)
ALTER TABLE dbo.ORDERR ADD PRIMARY KEY (idOrder)
ALTER TABLE dbo.INCLUDEE ADD PRIMARY KEY (idPacket, idSupply)
ALTER TABLE dbo.PROVINCE ADD PRIMARY KEY (idProvince)
ALTER TABLE dbo.DISTRICT ADD PRIMARY KEY (idDistrict)
ALTER TABLE dbo.VILLAGE ADD PRIMARY KEY (idVillage)

/*SET FOREIGN KEY*/
ALTER TABLE dbo.MANAGER ADD FOREIGN KEY (idManager) REFERENCES dbo.ACCOUNT (userName)

ALTER TABLE dbo.PATIENT ADD FOREIGN KEY (idPatient) REFERENCES dbo.ACCOUNT (userName)
ALTER TABLE dbo.PATIENT ADD FOREIGN KEY (idProvince) REFERENCES dbo.PROVINCE (idProvince)
ALTER TABLE dbo.PATIENT ADD FOREIGN KEY (idDistrict) REFERENCES dbo.DISTRICT (idDistrict)
ALTER TABLE dbo.PATIENT ADD FOREIGN KEY (idVillage) REFERENCES dbo.VILLAGE (idVillage)

ALTER TABLE dbo.LIST_PATIENT ADD FOREIGN KEY (idPatient1) REFERENCES dbo.PATIENT (idPatient)
ALTER TABLE dbo.LIST_PATIENT ADD FOREIGN KEY (idPatient2) REFERENCES dbo.PATIENT (idPatient)

ALTER TABLE dbo.HISTORY_PROCESS ADD FOREIGN KEY (idPatient) REFERENCES dbo.PATIENT (idPatient)
ALTER TABLE dbo.HISTORY_PROCESS ADD FOREIGN KEY (idPlace) REFERENCES dbo.PLACE_OF_STATEMENT (idPlace)

ALTER TABLE dbo.SUPPLY ADD FOREIGN KEY (idManager) REFERENCES dbo.MANAGER (idManager)

ALTER TABLE dbo.PACKET_SUPPLY ADD FOREIGN KEY (idManager) REFERENCES dbo.MANAGER (idManager)

ALTER TABLE dbo.INCLUDEE ADD FOREIGN KEY (idPacket) REFERENCES dbo.PACKET_SUPPLY (idPacket)
ALTER TABLE dbo.INCLUDEE ADD FOREIGN KEY (idSupply) REFERENCES dbo.SUPPLY (idSupply)

ALTER TABLE dbo.ORDERR ADD FOREIGN KEY (idManager) REFERENCES dbo.MANAGER (idManager)
ALTER TABLE dbo.ORDERR ADD FOREIGN KEY (idPatient) REFERENCES dbo.PATIENT (idPatient)
ALTER TABLE dbo.ORDERR ADD FOREIGN KEY (idProduce) REFERENCES dbo.PACKET_SUPPLY (idPacket)

